-- Carrtell RC1-03: independent admin login + RBAC
create extension if not exists pgcrypto;

create table if not exists public.admin_roles (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (name ~ '^[a-z0-9_\-]{2,50}$'),
  title text not null,
  description text,
  permissions text[] not null default '{}',
  is_system boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_accounts (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[a-z0-9_.\-]{3,40}$'),
  full_name text not null,
  email text,
  role_id uuid references public.admin_roles(id) on delete set null,
  is_active boolean not null default true,
  is_super_admin boolean not null default false,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text,
  entity_id text,
  meta jsonb not null default '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists admin_activity_logs_actor_created_idx on public.admin_activity_logs(actor_id, created_at desc);
create index if not exists admin_accounts_role_idx on public.admin_accounts(role_id);

insert into public.admin_roles(name,title,description,permissions,is_system)
values
('owner','مالک سیستم','دسترسی کامل و غیرقابل محدودسازی',array['*'],true),
('manager','مدیر فروشگاه','مدیریت فروشگاه، سفارش‌ها و مشتریان',array['dashboard.view','orders.view','orders.manage','products.view','products.manage','inventory.view','inventory.manage','customers.view','customers.manage','support.view','support.manage','content.view','content.manage','dispatch.view','dispatch.manage'],true),
('warehouse','انباردار','محصولات و موجودی',array['dashboard.view','products.view','inventory.view','inventory.manage'],true),
('support','پشتیبان','مشتریان، سفارش‌ها و پشتیبانی',array['dashboard.view','orders.view','customers.view','support.view','support.manage'],true),
('accountant','حسابدار','مالی و گزارش‌ها',array['dashboard.view','orders.view','finance.view','finance.manage','audit.view'],true)
on conflict (name) do update set title=excluded.title,description=excluded.description,permissions=excluded.permissions,is_system=true,updated_at=now();

create or replace view public.admin_accounts_view as
select a.id,a.username,a.full_name,a.email,a.role_id,r.title as role_title,a.is_active,a.is_super_admin,a.last_login_at,a.created_at
from public.admin_accounts a left join public.admin_roles r on r.id=a.role_id;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_accounts a where a.id=auth.uid() and a.is_active=true)
$$;

create or replace function public.is_admin_user(p_user uuid) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_accounts a where a.id=p_user and a.is_active=true)
$$;

create or replace function public.is_super_admin(p_user uuid default auth.uid()) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_accounts a where a.id=p_user and a.is_active=true and a.is_super_admin=true)
$$;

create or replace function public.admin_has_permission(p_permission text, p_user uuid default auth.uid()) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.admin_accounts a
    left join public.admin_roles r on r.id=a.role_id
    where a.id=p_user and a.is_active=true
      and (a.is_super_admin=true or '*'=any(coalesce(r.permissions,'{}')) or p_permission=any(coalesce(r.permissions,'{}')))
  )
$$;

create or replace function public.get_my_admin_access()
returns table(username text,full_name text,email text,is_super_admin boolean,is_active boolean,role_id uuid,role_title text,permissions text[])
language plpgsql security definer set search_path=public as $$
begin
  update public.admin_accounts set last_login_at=now(),updated_at=now() where id=auth.uid() and is_active=true;
  return query select a.username,a.full_name,a.email,a.is_super_admin,a.is_active,a.role_id,r.title,
    case when a.is_super_admin then array['*']::text[] else coalesce(r.permissions,'{}'::text[]) end
  from public.admin_accounts a left join public.admin_roles r on r.id=a.role_id
  where a.id=auth.uid();
end $$;

create or replace function public.admin_log_event(p_action text,p_entity text default null,p_entity_id text default null,p_meta jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'admin access required'; end if;
  insert into public.admin_activity_logs(actor_id,action,entity,entity_id,meta)
  values(auth.uid(),p_action,p_entity,p_entity_id,coalesce(p_meta,'{}'::jsonb));
end $$;

alter table public.admin_roles enable row level security;
alter table public.admin_accounts enable row level security;
alter table public.admin_activity_logs enable row level security;

drop policy if exists "admin roles read" on public.admin_roles;
drop policy if exists "admin roles manage" on public.admin_roles;
drop policy if exists "admin accounts self or staff read" on public.admin_accounts;
drop policy if exists "admin accounts staff update" on public.admin_accounts;
drop policy if exists "admin logs read" on public.admin_activity_logs;
drop policy if exists "admin logs insert" on public.admin_activity_logs;

create policy "admin roles read" on public.admin_roles for select to authenticated using (public.is_admin());
create policy "admin roles manage" on public.admin_roles for all to authenticated using (public.admin_has_permission('roles.manage')) with check (public.admin_has_permission('roles.manage'));
create policy "admin accounts self or staff read" on public.admin_accounts for select to authenticated using (id=auth.uid() or public.admin_has_permission('staff.view'));
create policy "admin accounts staff update" on public.admin_accounts for update to authenticated using (public.admin_has_permission('staff.manage') and not is_super_admin) with check (public.admin_has_permission('staff.manage') and not is_super_admin);
create policy "admin logs read" on public.admin_activity_logs for select to authenticated using (public.admin_has_permission('audit.view'));
create policy "admin logs insert" on public.admin_activity_logs for insert to authenticated with check (actor_id=auth.uid() and public.is_admin());

grant execute on function public.get_my_admin_access() to authenticated;
grant execute on function public.admin_has_permission(text,uuid) to authenticated;
grant execute on function public.admin_log_event(text,text,text,jsonb) to authenticated;
grant select on public.admin_accounts_view to authenticated;

-- RC1-03B: one-place first-run setup. No CLI or Edge Function is required.
create or replace function public.admin_setup_status()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'setup_required', not exists(select 1 from public.admin_accounts),
    'admin_count', (select count(*) from public.admin_accounts)
  );
$$;

create or replace function public.bootstrap_first_super_admin(
  p_username text,
  p_password text,
  p_full_name text,
  p_email text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, extensions
as $$
declare
  v_username text := lower(trim(p_username));
  v_email text;
  v_user_id uuid;
  v_owner_role uuid;
  v_now timestamptz := now();
  v_existing_identity boolean := false;
begin
  -- Bootstrap permanently closes as soon as the first admin exists.
  if exists(select 1 from public.admin_accounts) then
    raise exception 'راه‌اندازی اولیه قبلاً انجام شده است';
  end if;

  if v_username !~ '^[a-z0-9_.\-]{3,40}$' then
    raise exception 'نام کاربری نامعتبر است';
  end if;
  if length(coalesce(p_password, '')) < 10 then
    raise exception 'رمز عبور باید حداقل ۱۰ کاراکتر باشد';
  end if;
  if length(trim(coalesce(p_full_name, ''))) < 2 then
    raise exception 'نام مدیر نامعتبر است';
  end if;

  v_email := coalesce(nullif(lower(trim(p_email)), ''), v_username || '@admin.carrtell.local');

  select id into v_owner_role from public.admin_roles where name = 'owner' limit 1;
  if v_owner_role is null then
    raise exception 'نقش مالک سیستم پیدا نشد؛ ابتدا Migration را کامل اجرا کنید';
  end if;

  -- Reuse an existing Auth user when a previous patch already created it.
  -- This avoids forcing the owner to visit another dashboard or delete users manually.
  select id into v_user_id
  from auth.users
  where lower(email) = v_email
  order by created_at asc
  limit 1;

  if v_user_id is null then
    v_user_id := gen_random_uuid();

    insert into auth.users (
      instance_id, id, aud, role, email, encrypted_password,
      email_confirmed_at, invited_at, confirmation_token,
      recovery_token, email_change_token_new, email_change,
      raw_app_meta_data, raw_user_meta_data,
      created_at, updated_at, is_super_admin
    ) values (
      '00000000-0000-0000-0000-000000000000', v_user_id,
      'authenticated', 'authenticated', v_email,
      crypt(p_password, gen_salt('bf')),
      v_now, v_now, '', '', '', '',
      jsonb_build_object('provider','email','providers',array['email'],'carrtell_admin',true),
      jsonb_build_object('username',v_username,'full_name',trim(p_full_name)),
      v_now, v_now, false
    );
  else
    update auth.users
    set encrypted_password = crypt(p_password, gen_salt('bf')),
        email_confirmed_at = coalesce(email_confirmed_at, v_now),
        raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
          || jsonb_build_object('provider','email','providers',array['email'],'carrtell_admin',true),
        raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
          || jsonb_build_object('username',v_username,'full_name',trim(p_full_name)),
        updated_at = v_now
    where id = v_user_id;
  end if;

  select exists(select 1 from auth.identities where user_id = v_user_id and provider = 'email')
  into v_existing_identity;

  if not v_existing_identity then
    insert into auth.identities (
      id, user_id, identity_data, provider, provider_id,
      last_sign_in_at, created_at, updated_at
    ) values (
      gen_random_uuid(), v_user_id,
      jsonb_build_object('sub',v_user_id::text,'email',v_email,'email_verified',true),
      'email', v_user_id::text, v_now, v_now, v_now
    );
  end if;

  insert into public.admin_accounts (
    id, username, full_name, email, role_id, is_active, is_super_admin
  ) values (
    v_user_id, v_username, trim(p_full_name), v_email, v_owner_role, true, true
  )
  on conflict (id) do update set
    username = excluded.username,
    full_name = excluded.full_name,
    email = excluded.email,
    role_id = excluded.role_id,
    is_active = true,
    is_super_admin = true,
    updated_at = now();

  insert into public.admin_activity_logs(actor_id, action, entity, entity_id, meta)
  values(v_user_id, 'bootstrap_super_admin', 'admin_account', v_user_id::text,
    jsonb_build_object('username',v_username,'source','carrtell_first_run_setup'));

  return jsonb_build_object(
    'success', true,
    'username', v_username,
    'email', v_email,
    'message', 'حساب Super Admin آماده شد'
  );
exception
  when unique_violation then
    raise exception 'نام کاربری یا ایمیل با حساب مدیریتی دیگری تداخل دارد';
end;
$$;

revoke all on function public.bootstrap_first_super_admin(text,text,text,text) from public;
grant execute on function public.bootstrap_first_super_admin(text,text,text,text) to anon, authenticated;
grant execute on function public.admin_setup_status() to anon, authenticated;
